### ISSUE TITLE
Gutenberg compatible

### ISSUE THREAD

**Issue by typometre** [electricbookworks/paged-wp#7]
Hi,
Have fork and proposed a pull #6  to transform the insertion of the preview button from the old hook to a metabox.
This make the plugin compatible with the new Gutenberg Editor.
It would also make easier to start thinking and implementing other option in this metabox panel. 
Code could be cleaner (not an expert), and this metabox is not pure gutenberg but gutenberg compatible but it does the job and let us provide Paged.js in both classic and gutenberg editor.

**Comment by arthurattwell** [comment]
This has been done in #10.
